/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "math.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}
