/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATH_H_RPCGEN
#define _MATH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int n;
};
typedef struct data data;

#define FIBSUM 0x312FDE78
#define FIBSUM_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIBNUMB 1
extern  int * fibnumb_1(data *, CLIENT *);
extern  int * fibnumb_1_svc(data *, struct svc_req *);
#define SUM 2
extern  int * sum_1(data *, CLIENT *);
extern  int * sum_1_svc(data *, struct svc_req *);
extern int fibsum_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIBNUMB 1
extern  int * fibnumb_1();
extern  int * fibnumb_1_svc();
#define SUM 2
extern  int * sum_1();
extern  int * sum_1_svc();
extern int fibsum_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATH_H_RPCGEN */
