/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math.h"


void
fibsum_1(char *host, int a)
{
	CLIENT *clnt;
	int  *result_1;
	data  fibnumb_1_arg;
	int  *result_2;
	data  sum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FIBSUM, FIBSUM_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	fibnumb_1_arg.n = a;
	result_1 = fibnumb_1(&fibnumb_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("The index %d of a fib sequence is the number %d\n", a, *result_1);

	sum_1_arg.n = a;
	result_2 = sum_1(&sum_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("The sum of all the positive number up till %d is %d\n", a, *result_2);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fibsum_1 (host, atoi(argv[2]));
exit (0);
}
