/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math.h"

int *
fibnumb_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;

	int var1 = 0;
    int var2 = 1;
    result = var2;
    if((argp->n) == 1){
        result = var1;
    }else if((argp->n)==2){
		result = var2;
	}else{
		int i;
    	for(i=3; i<=(argp->n); i++){
        	result = var1 + var2;
        	var1 = var2;
        	var2 = result;
    	}
	}
	
	//result = holdResult;

	return &result;
}

int *
sum_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;

	result = 0;
	int i;
    for(i=1; i<= (argp->n); i++){
        result += i;
    }
    //return result;
	//result = holdResult;

	return &result;
}
